/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 09/Apr/2021 21:48:49
** YOU CAN MODIFY IT, as it will not be regenerated.
** If you want to regenrate this file simply delete it.
*/
using System;
using System.Collections.Generic;
using uPromis.Microservice.ContractAPI.Models;

namespace uPromis.Microservice.ContractAPI.Business
{
    partial class ClientBusinessRules : IClientBusinessRules
    {
        partial void OnApplyBusinessRules(Models.Client Record, Models.ClientDTO DTORecord, IRepository<Models.Client> Repository)
        {

        }
    }
}
