/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 06/Sep/2021 21:24:57
** YOU CAN MODIFY IT, as it will not be regenerated.
** If you want to regenrate this file simply delete it.
*/
using System;
using System.Collections.Generic;
using System.Security.Claims;
using uPromis.Service.Business;
using uPromis.Services.Models;
using uPromis.Microservice.ProjectAPI.Models;

namespace uPromis.Microservice.ProjectAPI.Business
{
    partial class ProgrammeBusinessRules : IProgrammeBusinessRules
    {
        partial void OnApplyBusinessRules(Models.Programme Record, ProgrammeDTO DTORecord, ClaimsPrincipal user)
        {

        }
    }
}
