/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 05/Sep/2021 18:50:32
** YOU CAN MODIFY IT, as it will not be regenerated.
** If you want to regenrate this file simply delete it.
*/
using System;
using System.Collections.Generic;
using System.Security.Claims;
using uPromis.Service.Business;
using uPromis.Services.Models;
using uPromis.Microservice.ProjectAPI.Models;

namespace uPromis.Microservice.ProjectAPI.Business
{
    partial class ProjectBusinessRules : IProjectBusinessRules
    {
        partial void OnApplyBusinessRules(Models.Project Record, ProjectDTO DTORecord, ClaimsPrincipal user)
        {

        }
    }
}
