/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 09/May/2021 22:04:34
** YOU CAN MODIFY IT, as it will not be regenerated.
** If you want to regenrate this file simply delete it.
*/
using System;
using System.Collections.Generic;
using System.Security.Claims;
using uPromis.Service.Business;
using uPromis.Services.Models;
using uPromis.Microservice.Notification.Models;

namespace uPromis.Microservice.Notification.Business
{
    partial class NotificationGroupBusinessRules : INotificationGroupBusinessRules
    {
        partial void OnApplyBusinessRules(Models.NotificationGroup Record, NotificationGroupDTO DTORecord, ClaimsPrincipal user)
        {

        }
    }
}
