/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 08/May/2021 16:36:32
** YOU CAN MODIFY IT, as it will not be regenerated.
** If you want to regenrate this file simply delete it.
*/
using System;
using System.Collections.Generic;
using System.Security.Claims;
using uPromis.Service.Business;
using uPromis.Microservice.Notification.Models;
using uPromis.Services.Models;

namespace uPromis.Microservice.Notification.Business
{
    partial class NotificationEntryBusinessRules : INotificationEntryBusinessRules
    {
        partial void OnApplyBusinessRules(Models.NotificationEntry Record, NotificationEntryDTO DTORecord, ClaimsPrincipal user)
        {

        }
    }
}
