//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uPromis.Microservice.Notification.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uPromis.Microservice.Notification.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {Name},&lt;/p&gt;
        ///&lt;p&gt;Here is the list of &lt;strong&gt;Contract items&lt;/strong&gt; for which you have an action to take. Keep your project under control.&lt;/p&gt;
        ///&lt;p&gt;
        ///    {ItemsTable}
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Getting updates too often? Not often enough? Configure notification settings in Your Profile (&lt;a href=&quot;https://www.u-ProMIS.unisys.com&quot; target=&quot;_blank&quot;&gt;My Details&lt;/a&gt;)
        ///&lt;/p&gt;.
        /// </summary>
        internal static string ContractReminderMailItem {
            get {
                return ResourceManager.GetString("ContractReminderMailItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; style=&quot;margin: 0;padding: 0;font-family: &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Helvetica, Arial, sans-serif;box-sizing: border-box;font-size: 14px;&quot;&gt;
        ///
        ///&lt;head style=&quot;margin: 0;padding: 0;font-family: &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Helvetica, Arial, sans-serif;box-sizing: border-box;font-size: 14px;&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; style=&quot;margin: 0;padding: 0;font-family: &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Helve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailMasterTemplate {
            get {
                return ResourceManager.GetString("EmailMasterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string mailAuthenticationNeeded {
            get {
                return ResourceManager.GetString("mailAuthenticationNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string mailPassword {
            get {
                return ResourceManager.GetString("mailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uPromis@unisys.com.
        /// </summary>
        internal static string mailSender {
            get {
                return ResourceManager.GetString("mailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1.
        /// </summary>
        internal static string mailServer {
            get {
                return ResourceManager.GetString("mailServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7825.
        /// </summary>
        internal static string mailServerPort {
            get {
                return ResourceManager.GetString("mailServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string mailUsername {
            get {
                return ResourceManager.GetString("mailUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {Name},&lt;/p&gt;
        ///&lt;p&gt;Here is the list of &lt;strong&gt;Project items&lt;/strong&gt; for which you have an action to take. Keep your project under control.&lt;/p&gt;
        ///&lt;p&gt;
        ///    {ItemsTable}
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Getting updates too often? Not often enough? Configure notification settings in Your Profile (&lt;a href=&quot;https://www.u-ProMIS.unisys.com&quot; target=&quot;_blank&quot;&gt;My Details&lt;/a&gt;)
        ///&lt;/p&gt;.
        /// </summary>
        internal static string ProjectReminderMailItem {
            get {
                return ResourceManager.GetString("ProjectReminderMailItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {Name},&lt;/p&gt;
        ///&lt;p&gt;Here is the list of &lt;strong&gt;Activities, Event or Action items&lt;/strong&gt; for which you have an action to perform. Keep your project under control.&lt;/p&gt;
        ///&lt;p&gt;
        ///    {ItemsTable}
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Getting updates too often? Not often enough? Configure notification settings in Your Profile (&lt;a href=&quot;https://www.u-ProMIS.unisys.com&quot; target=&quot;_blank&quot;&gt;My Details&lt;/a&gt;)
        ///&lt;/p&gt;.
        /// </summary>
        internal static string ReminderMailItem {
            get {
                return ResourceManager.GetString("ReminderMailItem", resourceCulture);
            }
        }
    }
}
